// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/translation.proto

package translatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== REQUEST =====
type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // original text (e.g., "hello world")
	FromLang      string                 `protobuf:"bytes,2,opt,name=from_lang,json=fromLang,proto3" json:"from_lang,omitempty"`
	Langs         []string               `protobuf:"bytes,3,rep,name=langs,proto3" json:"langs,omitempty"` // target languages for translation (e.g., ["uk", "ru"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translation_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetFromLang() string {
	if x != nil {
		return x.FromLang
	}
	return ""
}

func (x *TranslateRequest) GetLangs() []string {
	if x != nil {
		return x.Langs
	}
	return nil
}

// ===== RESPONSE =====
type TranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  map[string]string      `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {"en": "...", "uk": "...", "ru": "..."}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translation_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetTranslations() map[string]string {
	if x != nil {
		return x.Translations
	}
	return nil
}

var File_proto_translation_proto protoreflect.FileDescriptor

const file_proto_translation_proto_rawDesc = "" +
	"\n" +
	"\x17proto/translation.proto\x12\n" +
	"translator\"Y\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tfrom_lang\x18\x02 \x01(\tR\bfromLang\x12\x14\n" +
	"\x05langs\x18\x03 \x03(\tR\x05langs\"\xa9\x01\n" +
	"\x11TranslateResponse\x12S\n" +
	"\ftranslations\x18\x01 \x03(\v2/.translator.TranslateResponse.TranslationsEntryR\ftranslations\x1a?\n" +
	"\x11TranslationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012]\n" +
	"\x11TranslatorService\x12H\n" +
	"\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x1d.translator.TranslateResponseB\x1cZ\x1ago-translator/translatorpbb\x06proto3"

var (
	file_proto_translation_proto_rawDescOnce sync.Once
	file_proto_translation_proto_rawDescData []byte
)

func file_proto_translation_proto_rawDescGZIP() []byte {
	file_proto_translation_proto_rawDescOnce.Do(func() {
		file_proto_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_translation_proto_rawDesc), len(file_proto_translation_proto_rawDesc)))
	})
	return file_proto_translation_proto_rawDescData
}

var file_proto_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_translation_proto_goTypes = []any{
	(*TranslateRequest)(nil),  // 0: translator.TranslateRequest
	(*TranslateResponse)(nil), // 1: translator.TranslateResponse
	nil,                       // 2: translator.TranslateResponse.TranslationsEntry
}
var file_proto_translation_proto_depIdxs = []int32{
	2, // 0: translator.TranslateResponse.translations:type_name -> translator.TranslateResponse.TranslationsEntry
	0, // 1: translator.TranslatorService.Translate:input_type -> translator.TranslateRequest
	1, // 2: translator.TranslatorService.Translate:output_type -> translator.TranslateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_translation_proto_init() }
func file_proto_translation_proto_init() {
	if File_proto_translation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_translation_proto_rawDesc), len(file_proto_translation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translation_proto_goTypes,
		DependencyIndexes: file_proto_translation_proto_depIdxs,
		MessageInfos:      file_proto_translation_proto_msgTypes,
	}.Build()
	File_proto_translation_proto = out.File
	file_proto_translation_proto_goTypes = nil
	file_proto_translation_proto_depIdxs = nil
}
