name: Auto Fix Issue

on:
  issues:
    types: [opened]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies for embedding
        working-directory: ./.github/actions/issue-analyzer
        run: npm install @xenova/transformers chromadb

      - name: Query embeddings to Chroma
        env:
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
          CHROMA_TENANT: ${{ secrets.CHROMA_TENANT }}
          CHROMA_DATABASE: ${{ secrets.CHROMA_DATABASE }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        working-directory: ./.github/actions/issue-analyzer
        run: node query-embeddings.js

      - name: Run Issue Analyzer
        env:
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
          CHROMA_TENANT: ${{ secrets.CHROMA_TENANT }}
          CHROMA_DATABASE: ${{ secrets.CHROMA_DATABASE }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_BODY: ${{ github.event.issue.body || github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        working-directory: ./.github/actions/issue-analyzer
        run: node index.js
