name: Vectorize Repository (HF)

on:
  workflow_dispatch:

jobs:
  vectorize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd ./.github/actions/vectorize
          npm install

      - name: Run Vectorization Action
        run: node ./.github/actions/vectorize/index.js
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
          CHROMA_TENANT: ${{ secrets.CHROMA_TENANT }}
          CHROMA_DATABASE: 'Test'

