name: Vectorize Repository (Local)

on:
  workflow_dispatch:

jobs:
  vectorize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd ./.github/actions/vectorize
          npm ci
          npm rebuild sharp --platform=linux --arch=x64 --verbose

      - name: Run Vectorization Action
        run: node ./.github/actions/vectorize/index.js
        env:
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
          CHROMA_TENANT: ${{ secrets.CHROMA_TENANT }}
          CHROMA_DATABASE: ${{ secrets.CHROMA_DATABASE }}
          COLLECTION_ID: ${{ secrets.COLLECTION_ID }}



